CREATE TABLE IF NOT EXISTS pref_config(
	id INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(30) NOT NULL,
	value TEXT NOT NULL,
	autoload INT(1) NOT NULL DEFAULT 0
)DEFAULT CHARSET = UTF8;
CREATE TABLE IF NOT EXISTS pref_users(
	id INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
	nickname VARCHAR(16) NOT NULL,
	email VARCHAR(50) NOT NULL,
	password CHAR(128) NOT NULL,
	salt CHAR(128) NOT NULL,
	ip VARCHAR(15) NOT NULL,
	created DATETIME NOT NULL DEFAULT '2017-01-01 00:00:00',
	updated DATETIME NOT NULL DEFAULT '2017-01-01 00:00:00',
	state INT(1) NOT NULL DEFAULT 1,
	role INT(2) NOT NULL DEFAULT 1
)DEFAULT CHARSET = UTF8;
CREATE TABLE IF NOT EXISTS pref_profiles(
	id INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(30) NOT,
	gender INT(1) NOT NULL DEFAULT 0,
	birthday DATETIME NOT NULL DEFAULT '2017-01-01 00:00:00',
	descrip VARCHAR(250) NOT NULL,
	site VARCHAR(60) NOT NULL,
	social TEXT NOT NULL,
	avatar VARCHAR(250) NOT NULL,
	avatarlocal VARCHAR(250) NOT NULL,
	cover VARCHAR(250) NOT NULL,
	coverlocal VARCHAR(250) NOT NULL
)DEFAULT CHARSET = UTF8;
CREATE TABLE IF NOT EXISTS pref_users_attempts(
	id INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
	time VARCHAR(10) NOT NULL,
	user INT(11) NOT NULL DEFAULT 0
)DEFAULT CHARSET = UTF8;
CREATE TABLE IF NOT EXISTS pref_posts(
	id INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
	title VARCHAR(250) NOT NULL,
	slug VARCHAR(250) NOT NULL,
	permalink VARCHAR(250) NOT NULL,
	created DATETIME NOT NULL DEFAULT '2017-01-01 00:00:00',
	updated DATETIME NOT NULL DEFAULT '2017-01-01 00:00:00',
	descrip text NOT NULL,
	content TEXT NOT NULL,
	cat INT(11) NOT NULL DEFAULT 0,
	superior INT(11) NOT NULL DEFAULT 0,
	tags VARCHAR(250) NOT NULL,
	coverlocal VARCHAR(250) NOT NULL,
	cover VARCHAR(250) NOT NULL,
	autor INT(11) NOT NULL DEFAULT 1,
	state INT(2) NOT NULL DEFAULT 1,
	type VARCHAR(20) NOT NULL DEFAULT 'page',
	template VARCHAR(50) NOT NULL DEFAULT '',
	hits INT(11) NOT NULL DEFAULT 0,
	lang VARCHAR(20) NOT NULL DEFAULT 'es',
	verof INT(11) NOT NULL DEFAULT 0,
	publidate DATETIME NOT NULL DEFAULT '2017-01-01 00:00:00',
	visibility INT(2) NOT NULL DEFAULT 1,
	sticky INT(1) NOT NULL DEFAULT 0,
	suporder INT(11) NOT NULL DEFAULT 1,
	target INT(1) NOT NULL DEFAULT 0,
	specialtype VARCHAR(20) NOT NULL,
	FULLTEXT(title,descrip)
)ENGINE = MYISAM DEFAULT CHARSET = UTF8;
CREATE TABLE IF NOT EXISTS pref_cats(
	id INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
	title VARCHAR(70) NOT NULL,
	slug VARCHAR(70) NOT NULL,
	permalink VARCHAR(250) NOT NULL,
	descrip VARCHAR(70) NOT NULL,
	type VARCHAR(20) NOT NULL DEFAULT '1',
	superior INT(11) NOT NULL DEFAULT 0,
	cover VARCHAR(250) NOT NULL,
	state INT(2) NOT NULL DEFAULT 1,
	created DATETIME NOT NULL DEFAULT '2017-01-01 00:00:00',
	updated DATETIME NOT NULL DEFAULT '2017-01-01 00:00:00',
	total_post INT(11) NOT NULL DEFAULT 0,
	lang VARCHAR(20) NOT NULL DEFAULT 'es',
	verof INT(11) NOT NULL DEFAULT 0
)DEFAULT CHARSET = UTF8;
CREATE TABLE IF NOT EXISTS pref_ads_groups(
	id INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(70) NOT NULL,
	descrip VARCHAR(70) NOT NULL,
	type VARCHAR(20) NOT NULL,
	section VARCHAR(20) NOT NULL,
	state INT(2) NOT NULL DEFAULT 1,
	needle INT(2) NOT NULL DEFAULT 1
)DEFAULT CHARSET = UTF8;
CREATE TABLE IF NOT EXISTS pref_ads(
	id INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
	groupid INT(11) NOT NULL DEFAULT 0,
	title VARCHAR(70) NOT NULL,
	link VARCHAR(250) NOT NULL,
	datestart DATETIME NOT NULL DEFAULT '2017-01-01 00:00:00',
	dateend DATETIME NOT NULL DEFAULT '2017-01-01 00:00:00',
	customdate INT(2) NOT NULL DEFAULT 0,
	descrip VARCHAR(250) NOT NULL,
	content TEXT NOT NULL,
	autor INT(11) NOT NULL DEFAULT 1,
	state INT(2) NOT NULL DEFAULT 1,
	type VARCHAR(20) NOT NULL,
	hits INT(11) NOT NULL DEFAULT 0,
	clicks INT(11) NOT NULL DEFAULT 0
)DEFAULT CHARSET = UTF8;
CREATE TABLE IF NOT EXISTS pref_collections(
	id INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
	title VARCHAR(70) NOT NULL,
	slug VARCHAR(70) NOT NULL,
	permalink VARCHAR(250) NOT NULL,
	descrip VARCHAR(70) NOT NULL,
	type varchar(40) NOT NULL DEFAULT 0,
	superior INT(11) NOT NULL DEFAULT 0,
	suporder INT(11) NOT NULL DEFAULT 1,
	cover VARCHAR(250) NOT NULL,
	image VARCHAR(250) NOT NULL,
	state INT(2) NOT NULL DEFAULT 1,
	count INT(11) NOT NULL DEFAULT 0,
	lang VARCHAR(20) NOT NULL DEFAULT 'es',
	verof INT(11) NOT NULL DEFAULT 0
)DEFAULT CHARSET = UTF8;
CREATE TABLE IF NOT EXISTS pref_collections_rel(
	id INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
	post_id INT(11) NOT NULL DEFAULT 0,
	collection_id INT(11) NOT NULL DEFAULT 0
)DEFAULT CHARSET = UTF8;
