CREATE TABLE IF NOT EXISTS pref_config(
	id INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(30) NOT NULL DEFAULT '',
	value TEXT NOT NULL,
	autoload INT(1) NOT NULL DEFAULT 0
)DEFAULT CHARSET = UTF8;
CREATE TABLE IF NOT EXISTS pref_users(
	id INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
	nickname VARCHAR(16) NOT NULL DEFAULT '',
	email VARCHAR(50) NOT NULL DEFAULT '',
	password CHAR(128) NOT NULL DEFAULT '',
	salt CHAR(128) NOT NULL DEFAULT '',
	ip VARCHAR(15) NOT NULL DEFAULT '',
	created DATETIME NOT NULL DEFAULT '2017-01-01 00:00:00',
	updated DATETIME NOT NULL DEFAULT '2017-01-01 00:00:00',
	state INT(1) NOT NULL DEFAULT 1,
	role INT(2) NOT NULL DEFAULT 1
)DEFAULT CHARSET = UTF8;
CREATE TABLE IF NOT EXISTS pref_profiles(
	id INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(30) NOT NULL DEFAULT '',
	gender INT(1) NOT NULL DEFAULT 0,
	birthday DATETIME NOT NULL DEFAULT '2017-01-01 00:00:00',
	descrip VARCHAR(250) NOT NULL DEFAULT '',
	site VARCHAR(60) NOT NULL DEFAULT '',
	social TEXT NOT NULL,
	avatar VARCHAR(250) NOT NULL DEFAULT '',
	avatarlocal VARCHAR(250) NOT NULL DEFAULT '',
	cover VARCHAR(250) NOT NULL DEFAULT '',
	coverlocal VARCHAR(250) NOT NULL DEFAULT ''
)DEFAULT CHARSET = UTF8;
CREATE TABLE IF NOT EXISTS pref_users_attempts(
	id INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
	time VARCHAR(10) NOT NULL DEFAULT '',
	user INT(11) NOT NULL DEFAULT 0
)DEFAULT CHARSET = UTF8;
CREATE TABLE IF NOT EXISTS pref_posts(
	id INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
	title VARCHAR(250) NOT NULL DEFAULT '',
	slug VARCHAR(250) NOT NULL DEFAULT '',
	permalink VARCHAR(250) NOT NULL DEFAULT '',
	created DATETIME NOT NULL DEFAULT '2017-01-01 00:00:00',
	updated DATETIME NOT NULL DEFAULT '2017-01-01 00:00:00',
	descrip text NOT NULL,
	content TEXT NOT NULL,
	cat INT(11) NOT NULL DEFAULT 0,
	superior INT(11) NOT NULL DEFAULT 0,
	tags VARCHAR(250) NOT NULL DEFAULT '',
	coverlocal VARCHAR(250) NOT NULL DEFAULT '',
	cover VARCHAR(250) NOT NULL DEFAULT '',
	autor INT(11) NOT NULL DEFAULT 1,
	state INT(2) NOT NULL DEFAULT 1,
	type VARCHAR(20) NOT NULL DEFAULT 'page',
	template VARCHAR(50) NOT NULL DEFAULT '',
	hits INT(11) NOT NULL DEFAULT 0,
	lang VARCHAR(20) NOT NULL DEFAULT 'es',
	verof INT(11) NOT NULL DEFAULT 0,
	publidate DATETIME NOT NULL DEFAULT '2017-01-01 00:00:00',
	visibility INT(2) NOT NULL DEFAULT 1,
	sticky INT(1) NOT NULL DEFAULT 0,
	suporder INT(11) NOT NULL DEFAULT 1,
	target INT(1) NOT NULL DEFAULT 0,
	specialtype VARCHAR(20) NOT NULL DEFAULT '',
	FULLTEXT(title,descrip)
)ENGINE = MYISAM DEFAULT CHARSET = UTF8;
CREATE TABLE IF NOT EXISTS pref_cats(
	id INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
	title VARCHAR(70) NOT NULL DEFAULT '',
	slug VARCHAR(70) NOT NULL DEFAULT '',
	permalink VARCHAR(250) NOT NULL DEFAULT '',
	descrip VARCHAR(70) NOT NULL DEFAULT '',
	type VARCHAR(20) NOT NULL DEFAULT '1',
	superior INT(11) NOT NULL DEFAULT 0,
	cover VARCHAR(250) NOT NULL DEFAULT '',
	state INT(2) NOT NULL DEFAULT 1,
	created DATETIME NOT NULL DEFAULT '2017-01-01 00:00:00',
	updated DATETIME NOT NULL DEFAULT '2017-01-01 00:00:00',
	total_post INT(11) NOT NULL DEFAULT 0,
	lang VARCHAR(20) NOT NULL DEFAULT 'es',
	verof INT(11) NOT NULL DEFAULT 0
)DEFAULT CHARSET = UTF8;
CREATE TABLE IF NOT EXISTS pref_ads_groups(
	id INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(70) NOT NULL DEFAULT '',
	descrip VARCHAR(70) NOT NULL DEFAULT '',
	type VARCHAR(20) NOT NULL DEFAULT '',
	section VARCHAR(20) NOT NULL DEFAULT '',
	state INT(2) NOT NULL DEFAULT 1,
	needle INT(2) NOT NULL DEFAULT 1
)DEFAULT CHARSET = UTF8;
CREATE TABLE IF NOT EXISTS pref_ads(
	id INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
	groupid INT(11) NOT NULL DEFAULT 0,
	title VARCHAR(70) NOT NULL DEFAULT '',
	link VARCHAR(250) NOT NULL DEFAULT '',
	datestart DATETIME NOT NULL DEFAULT '2017-01-01 00:00:00',
	dateend DATETIME NOT NULL DEFAULT '2017-01-01 00:00:00',
	customdate INT(2) NOT NULL DEFAULT 0,
	descrip VARCHAR(250) NOT NULL DEFAULT '',
	content TEXT NOT NULL,
	autor INT(11) NOT NULL DEFAULT 1,
	state INT(2) NOT NULL DEFAULT 1,
	type VARCHAR(20) NOT NULL DEFAULT '',
	hits INT(11) NOT NULL DEFAULT 0,
	clicks INT(11) NOT NULL DEFAULT 0
)DEFAULT CHARSET = UTF8;
CREATE TABLE IF NOT EXISTS pref_collections(
	id INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
	title VARCHAR(70) NOT NULL DEFAULT '',
	slug VARCHAR(70) NOT NULL DEFAULT '',
	permalink VARCHAR(250) NOT NULL DEFAULT '',
	descrip VARCHAR(70) NOT NULL DEFAULT '',
	type varchar(40) NOT NULL DEFAULT 0,
	superior INT(11) NOT NULL DEFAULT 0,
	suporder INT(11) NOT NULL DEFAULT 1,
	cover VARCHAR(250) NOT NULL DEFAULT '',
	image VARCHAR(250) NOT NULL DEFAULT '',
	state INT(2) NOT NULL DEFAULT 1,
	count INT(11) NOT NULL DEFAULT 0,
	lang VARCHAR(20) NOT NULL DEFAULT 'es',
	verof INT(11) NOT NULL DEFAULT 0
)DEFAULT CHARSET = UTF8;
CREATE TABLE IF NOT EXISTS pref_collections_rel(
	id INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
	post_id INT(11) NOT NULL DEFAULT 0,
	collection_id INT(11) NOT NULL DEFAULT 0
)DEFAULT CHARSET = UTF8;
